#!/bin/zsh

echo "Installing the calculator onto your system..."

CWD=$(pwd)
ENV=$(pwd)/bin/activate
COMMAND="python $CWD/calculator.py"

# Create the virtual environment and install the requirements
python -m venv .
source bin/activate
pip install -r requirements.txt

# Create the executable
sudo echo "#!/bin/zsh" > /usr/local/bin/calc
sudo echo "source $ENV" >> /usr/local/bin/calc
sudo echo "$COMMAND" >> /usr/local/bin/calc
sudo chmod +x /usr/local/bin/calc

# Create desktop entry
sudo echo "[Desktop Entry]" > /usr/share/applications/calc.desktop
sudo echo "Name=Calculator" >> /usr/share/applications/calc.desktop
sudo echo "Exec=calc" >> /usr/share/applications/calc.desktop
sudo echo "Terminal=false" >> /usr/share/applications/calc.desktop
sudo echo "Icon=$CWD/icon.png" >> /usr/share/applications/calc.desktop
sudo echo "Type=Application" >> /usr/share/applications/calc.desktop
sudo echo "Categories=Utility;" >> /usr/share/applications/calc.desktop

echo "Done!"
