#!/bin/zsh

# Script must be ran as root.
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root"
    echo "Try 'sudo ./install'"
    exit 1
fi

# Check if eva is installed and install it if it isn't
eva="eva"
brew="brew"
port="port"
if ! command -v $eva &> /dev/null
then
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "Installing eva..."

        DISTRO=$(cat /etc/os-release | grep -oP '(?<=^ID=).+' | tr -d '"')

        if [[ $DISTRO == "arch" ]]; then
            sudo pacman -S eva
        elif [[ $DISTRO == "archarm" ]]; then
            sudo pacman -S eva
        elif [[ $DISTRO == "debian" ]]; then
            sudo apt install eva
        elif [[ $DISTRO == "centos" ]]; then
            sudo yum install eva
        elif [[ $DISTRO == "fedora" ]]; then
            sudo dnf install eva
        elif [[ $DISTRO == "ubuntu" ]]; then
            sudo apt install eva
        else
            echo "Your package manager is not supported"
            echo "eva could not be found"
            echo "Please install eva using your package manager before running this script"
            exit 1
        fi
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        echo "Installing eva..."

        if command -v $brew &> /dev/null
        then
            brew install eva
        elif command -v $port &> /dev/null
        then
            port install eva
        else
            echo "Neither HomeBrew or MacPorts are installed. Please install either before running this script."
            exit 1
        fi
    else
        echo "eva could not be found"
        echo "Please install eva before running this script"
        exit 1
    fi
fi

echo "Installing the calculator onto your system..."

# Get the current working directory and the virtual environment
CWD=$(pwd)
ENV=$(pwd)/bin/activate
COMMAND="python $CWD/calculator.py"

# Create the virtual environment and install the requirements
python -m venv .
source bin/activate
pip install -r requirements.txt

# Create the executable
sudo echo "#!/bin/zsh" > /usr/local/bin/calc
sudo echo "source $ENV" >> /usr/local/bin/calc
sudo echo "$COMMAND" >> /usr/local/bin/calc
sudo chmod +x /usr/local/bin/calc

# Add desktop entries (OS specific)
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Create desktop entry
    sudo echo "[Desktop Entry]" > /usr/share/applications/calc.desktop
    sudo echo "Name=Calculator" >> /usr/share/applications/calc.desktop
    sudo echo "Exec=calc" >> /usr/share/applications/calc.desktop
    sudo echo "Terminal=false" >> /usr/share/applications/calc.desktop
    sudo echo "Icon=$CWD/icon.png" >> /usr/share/applications/calc.desktop
    sudo echo "Type=Application" >> /usr/share/applications/calc.desktop
    sudo echo "Categories=Utility;" >> /usr/share/applications/calc.desktop

elif [[ "$OSTYPE" == "darwin"* ]]; then
    # TODO: Add MacOS support for desktop entry
    echo "MacOS support not yet implemented."
    echo "Calculator may be ran currently by running the `calc` command in the terminal."
fi

echo "Done!"
