#!/bin/zsh


# Script must be ran as root.
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root"
    echo "Try 'sudo ./install'"
    exit 1
fi

# Uninstall eva
eva="eva"
if command -v $eva &> /dev/null
then
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "Uninstalling eva..."

        DISTRO=$(cat /etc/os-release | grep -oP '(?<=^ID=).+' | tr -d '"')

        if [[ $DISTRO == "arch" ]]; then
            sudo pacman -Rsn eva
        elif [[ $DISTRO == "archarm" ]]; then
            sudo pacman -Rsn eva
        elif [[ $DISTRO == "debian" ]]; then
            sudo apt remove eva
        elif [[ $DISTRO == "centos" ]]; then
            sudo yum remove eva
        elif [[ $DISTRO == "fedora" ]]; then
            sudo dnf remove eva
        elif [[ $DISTRO == "ubuntu" ]]; then
            sudo apt remove eva
        else
            echo "Your package manager is not supported"
            echo "eva could not be uninstalled. Please uninstall eva manually using your package manager"
        fi
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        echo "Uninstalling eva..."
        brew uninstall eva
    fi
fi

echo "Uninstalling the calculator from your system..."


# Uninstall desktop entries (OS specific)
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    sudo rm /usr/share/applications/calculator.desktop
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # TODO: Add desktop entry uninstallation for macOS
    echo "Desktop entry installation/uninstallation for macOS is not supported yet"
fi

sudo rm /usr/local/bin/calc

cd ..
sudo rm -rf calculator

echo "Done!"
